apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  generateName: mpi-allpair-allreduce-hari
  namespace: gcr-admin
spec:
  queue: gcr-admin
  minAvailable: 3 # for gang scheduling requires minAvailable to be set to the total number of tasks
  plugins:
    ssh: []   # passwordless SSH + host files under /etc/volcano
    svc: []   # creates per-task headless Services when containerPorts are present
    env: []   # VC_* envs
  tasks:
    - name: server
      replicas: 1
      template:
        metadata:
          labels:
            app: allpair-mpi
            role: server
        spec:
          schedulerName: volcano
          restartPolicy: Never
          volumes:
            - name: dshm # use /dev/shm for inter-process communication
              emptyDir:
                medium: Memory
                sizeLimit: 100Gi
            - name: data
              persistentVolumeClaim:
                claimName: pvc-local-gcr-admin-01
          tolerations:
            - key: "rdma"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: allpair-mpi
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: server
              image: nvcr.io/nvidia/pytorch:25.06-py3
              env:
                - name: gcrnode
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: ALLPAIR_DEBUG
                  value: "1"
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: data
                  mountPath: /data
              ports:
                - name: rdma
                  containerPort: 18515
              command: ["/bin/bash","-lc"]
              args:
                - |
                  set -eo pipefail
                  git clone https://github.com/IamNirmata/Cluster-Validation-Runbook.git /opt/Cluster-Validation-Runbook
                  bash /opt/Cluster-Validation-Runbook/allpair/server.sh
              resources:
                requests:
                  nvidia.com/gpu: "8"
                  cpu: "180"
                  memory: "2500Gi"
                  rdma/rdma_shared_device_a: "1"
                limits:
                  nvidia.com/gpu: "8"
                  cpu: "180"
                  memory: "2500Gi"
                  rdma/rdma_shared_device_a: "1"
    - name: client
      replicas: 2
      template:
        metadata:
          labels:
            app: allpair-mpi
            role: client
        spec:
          schedulerName: volcano
          restartPolicy: Never
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 100Gi
            - name: data
              persistentVolumeClaim:
                claimName: pvc-local-gcr-admin-01
          tolerations:
            - key: "rdma"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: allpair-mpi
                  topologyKey: kubernetes.io/hostname
            # nodeAffinity:
            #   requiredDuringSchedulingIgnoredDuringExecution:
            #     nodeSelectorTerms:
            #       - matchExpressions:
            #           - key: kubernetes.io/hostname
            #             operator: In
            #             values:
            #               - "gcr_node_placeholder"
          containers:
            - name: client
              image: nvcr.io/nvidia/pytorch:25.06-py3
              env:
                - name: gcrnode
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: ALLPAIR_DEBUG
                  value: "1"
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: data
                  mountPath: /data
              ports:
                - name: rdma
                  containerPort: 18515
              command: ["/bin/bash","-lc"]
              args:
                - |
                  set -eo pipefail
                  git clone https://github.com/IamNirmata/Cluster-Validation-Runbook.git /opt/Cluster-Validation-Runbook
                  bash /opt/Cluster-Validation-Runbook/allpair/client.sh
              resources:
                requests:
                  nvidia.com/gpu: "8"
                  cpu: "180"
                  memory: "2500Gi"
                  rdma/rdma_shared_device_a: "1"
                limits:
                  nvidia.com/gpu: "8"
                  cpu: "180"
                  memory: "2500Gi"
                  rdma/rdma_shared_device_a: "1"
